Kizuna/API/urls.py
from django.urls import path, re_path, include
from . import views


# API for the Bizon365 hook that activates the process of importing users to the getcourse
api_patterns = [
    path('start/', views.InitialImportAPIView.as_view(), name="transfer-bizon-gk"),
]

# Paths responsible for manually importing viewers to getcourse
hand_import_patterns = [
    path('', views.HandImportView.as_view(), name="hand-import"),
    re_path(r'^list_webinar/(?P<wq>\d+)$', views.ExportWebroomListView.as_view(), name="get-bizon-web"),
    path('list_webinar/start_import', views.HandImportViewersListView.as_view(), name="start-hand-import"),
]

# Lists of already completed imports with details and start re-import
webroom_patterns = [
    path('', views.WebroomList.as_view(), name="my-webroom"),
    re_path(r'^detail/(?P<pk>\d+)$', views.WebroomDetail.as_view(), name="detail-webroom"),
    re_path(r'^detail/(?P<pk>\d+)/reimport$', views.ImportViewersListView.as_view(), name="reimport-webroom"),
    re_path(r'^detail/(?P<pk>\d+)/upload$', views.ExportViewersCSV.as_view(), name="upload-webroom"),
]

# Here the user sets his API keys for services
setting_patterns = [
    path('', views.SettingsDelayView.as_view(), name="setting-delay"),
    path('my', views.SettingsUpdateView.as_view(), name="setting"),
    path('my/bizon', views.SettingsBizonConnectView.as_view(), name="setting-bizon"),
]

# The section is responsible for corrupting users by downloading CSV
getcourse_import_patterns = [
    path('', views.CSVFileImportList.as_view(), name="my-import-getcourse"),
    path('import', views.DownloadedFileImportGetcourse.as_view(), name="import-getcourse"),
    re_path(r'^import/correct/(?P<pk>\d+)', views.ReimportFileGetcorse.as_view(), name="reimport-getcourse"),
    path('import/correct/', views.CorrectFileFieldImportGetcourse.as_view(), name="correct-field-getcourse"),
    path('import/correct/success', views.SuccessImportGetcourse.as_view(), name="success-import-getcourse"),
]

# The section converts files with tests to a convenient form
test_convert_patterns = [
    path('', views.TestUploadTestFormView.as_view(), name="upload_test"),
]

# The section create or update tracked session of webinar
session_pattern = [
    path('', views.WebroomSessionBizonListView.as_view(), name="list-session"),
    path('create', views.WebroomSessionCreateView.as_view(), name="session-create"),
    re_path(r'^(?P<pk>\d+)', views.SessionWebroomListView.as_view(), name="session-bizon"),
    re_path(r'^update/(?P<pk>\d+)', views.JoinTrackedSessionWithWebroom.as_view(),
            name="session-update"),
]

urlpatterns = [
    path('', views.index, name="index"),
    path('api/v1/', include(api_patterns)),
    path('my_webroom/', include(webroom_patterns)),
    path('hand_import/', include(hand_import_patterns)),
    path('setting', include(setting_patterns)),
    path('import_getcourse/', include(getcourse_import_patterns)),
    path('test_convert/', include(test_convert_patterns)),
    path('session/', include(session_pattern)),
]

Kizuna/Kizuna/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

# только на период разработки
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('API.urls')),
    path('admin/', admin.site.urls),
    # path('api/v1/', include('API.urls')),
    # path('general/', include('general.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
]

# только на период разработки
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Kizuna/API/models.py
import os.path

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import uuid

from Kizuna import settings


def get_default_field_token():
    return uuid.uuid4()


class TrackedSessinBizon(models.Model):
    """Tracked webinar sessions"""
    session = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    group_user = models.CharField(max_length=200)
    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        default=None,
        null=True
    )
    create = models.DateTimeField(auto_now_add=True)

    class META:
        ordering = ["create"]

    def __str__(self):
        return self.session

    def get_absolute_url(self):
        return reverse('session-bizon', args=[str(self.id)])

    def get_update_url(self):
        return reverse("session-update", args=[str(self.id)])


class WebroomTransaction(models.Model):
    """Model storing data about transferred webinars and their statuses"""

    event = models.CharField(max_length=200, verbose_name='Type_event')
    roomid = models.CharField(max_length=200, verbose_name='ID_number_webinar_room')
    webinarId = models.CharField(max_length=200, verbose_name='ID_webinar_event')
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    start_upload = models.BooleanField(default=False)
    result_upload = models.BooleanField(default=False)
    user_id = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        default=None,
        null=True
    )
    session = models.ForeignKey(
        TrackedSessinBizon,
        on_delete=models.SET_NULL,
        default=None,
        null=True
    )

    class META:
        ordering = ["create"]

    def get_absolute_url(self):
        return reverse('detail-webroom', args=[str(self.id)])

    def get_import_url(self):
        return reverse('reimport-webroom', args=[str(self.id)])

    def get_export_csv_url(self):
        return reverse('upload-webroom', args=[str(self.id)])

    def __str__(self):
        return self.webinarId


class TokenImport(models.Model):
    """Model storing tokens from user services"""

    token = models.UUIDField(primary_key=True,
                             default=get_default_field_token)
    token_gk = models.CharField(
        max_length=260,
        default=None,
        null=True
    )
    name_gk = models.CharField(
        max_length=200,
        default=None,
        null=True
    )
    token_bizon = models.CharField(
        max_length=2600,
        default=None,
        null=True
    )
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )

    class Meta:
        permissions = (("can_request", "Has request to GK, Bizon"),)
        ordering = ["create"]

    def __str__(self):
        return str(self.user)


class ViewersImport(models.Model):
    """Model storing data of transferred users"""

    name = models.CharField(
        max_length=200,
        default='Not found'
    )
    email = models.EmailField(max_length=200)
    phone = models.CharField(max_length=200)
    view = models.CharField(max_length=200)
    buttons = models.CharField(
        max_length=200,
        null=True
    )
    banners = models.CharField(
        max_length=200,
        null=True
    )
    create = models.DateTimeField(auto_now_add=True)
    import_to_gk = models.BooleanField(default=False)
    webroom = models.ForeignKey(
        WebroomTransaction,
        on_delete=models.CASCADE,
        null=True
    )

    class Meta:
        ordering = ["create"]

    def __str__(self):
        return self.email


class FileImportGetcourse(models.Model):
    """Model storing data of files loaded for import to getcourse"""

    file = models.FileField(upload_to=settings.DIRECTORY_FROM_FILE_IMPORT,
                            verbose_name="файл")
    date_load = models.DateTimeField(auto_now_add=True)
    group_user = models.CharField(max_length=200,
                                  default=None,
                                  verbose_name="группа_пользователей")
    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        default=None,
        null=True
    )

    class Meta:
        ordering = ["date_load"]

    def __str__(self):
        return os.path.basename(self.file.name)

    def get_import_url(self):
        return reverse('reimport-getcourse', args=[str(self.id)])

Kizuna/API/forms.py
import re

from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from API.core.import_logic import ConvertedTestCSV
from API.models import TokenImport, FileImportGetcourse, TrackedSessinBizon
from API.core.request_service import RequestBizon, RequestGetcorse
from Kizuna import settings


class QuantityWebroom(forms.Form):
    """Форма для ввода данных по выборке вебинаров"""

    quantity_webroom = forms.IntegerField(label="Количество вебинаров", initial=1,
                                          help_text="в диапазоне от 1 до 100",
                                          validators=[MinValueValidator(1), MaxValueValidator(100)])
    date_min = forms.DateField(label="Стартовая дата", help_text="Стартовая дата", required=False)
    date_max = forms.DateField(label="Конечная дата", help_text="Конечная дата", required=False)

    def clean_date_max(self):
        date_min = self.cleaned_data["date_min"]
        date_max = self.cleaned_data["date_max"]

        if not date_max:
            return date_max

        if date_min > date_max:
            raise ValidationError(_("Конечная дата должна быть больше стартовой"))

        return date_max


class SettingForm(ModelForm):
    """Форма внесение токенов внешних сервисов с проверкой их валидности"""

    class Meta:
        model = TokenImport
        fields = ["name_gk", "token_gk", "token_bizon"]

    def clean_name_gk(self) -> str:
        """Проверка валидности имени акканта Getcourse"""

        name_gk = self.cleaned_data["name_gk"]
        self.name_gk = name_gk
        if len(name_gk) < 3:
            raise ValidationError(_("Название Вашего аккаунта должно содержать "
                                    "больше 2 символов"))
        if self._valid_value(name_gk):
            raise ValidationError(_("Название Вашего аккаунта должно содержать "
                                    "и состоять из букв, цифр, - и _"))

        return name_gk

    def clean_token_bizon(self) -> str:
        token = self.cleaned_data["token_bizon"]
        if self._valid_value(token):
            raise ValidationError(_("Token должен содержать цифры, буквы, - и _"))

        if not RequestBizon.test_token_bizon(token):
            raise ValidationError(_("Bizon не подтвердил валидность Вашего token"))

        return token

    def clean_token_gk(self) -> str:
        token = self.cleaned_data["token_gk"]
        name_gk = self.name_gk
        if self._valid_value(token):
            raise ValidationError(_("Token должен содержать цифры, буквы, - и _"))

        if not RequestGetcorse.test_token_gk(token, name_gk):
            raise ValidationError(_("Getcourse не подтвердил валидность Вашего token"))

        return token

    def _valid_value(self, name: str) -> bool:
        return re.fullmatch(r'[0-9a-zA-Z_-]+', name) is None


class DownLoadedFileForm(ModelForm):
    """Отвечает за загрузку CSV файла с контактами студентов"""

    class Meta:
        model = FileImportGetcourse
        fields = ["file", "group_user"]

    def clean_file(self) -> str:
        file_name = self.cleaned_data["file"].name
        if not file_name.endswith(".csv"):
            raise ValidationError(_("Тип файла должен быть CSV"))

        return self.cleaned_data["file"]


class CorrectFieldsForm(forms.Form):
    """Форма уточнения выборки столбивков файла CSV для имяпорта в GC"""

    email = forms.ChoiceField()
    name = forms.ChoiceField()
    phone = forms.ChoiceField()


class DownLoadedTestFileForm(forms.Form):
    """Форма для загрузки файла конвертируемого тестирования"""

    file = forms.FileField(label="Ваш файл", help_text="Загрузите файл в формате CSV",)

    def clean_file(self) -> str:
        file = self.cleaned_data["file"]
        if not file.name.endswith(".csv"):
            raise ValidationError(_("Тип файла должен быть CSV"))

        return file


class CreateTrackedSessionForm(forms.ModelForm):
    """Create tracked session of webinar in model"""

    class Meta:
        model = TrackedSessinBizon
        fields = ["session", "description", "group_user"]
        labels = {
            "session": "URL вебинарной комнаты для отслеживания",
            "description": "Название сессии",
            "group_user": "Группа пользователей"
        }

    def clean_session(self) -> str:
        session = self.cleaned_data["session"]
        if re.fullmatch(r'https:\/\/start\.bizon365\.ru\/room\/\w+\/\w+', session) is None:
            raise ValidationError(_("После должно содержать валидную ссылку на "
                                    "вебинарную комнату, пример https://start.bizon365.ru/room/0000/name_web"))

        correct_session = session.split("/")
        return ":".join(correct_session[-2:])

Kizuna/API/templates/webroom/detail_webroom.html
{% extends "base_general_template.html" %}

{% block content %}
  <h1>Параметры: {{ webroom.webinarId }}</h1>


  <p><strong>Тип мероприятия:</strong> {{ webroom.event }}</p>
  <p><strong>Серийны номер:</strong> {{ webroom.roomid }}</p>
  <p><strong>Название:</strong> {{ webroom.webinarId }}</p>
  <p><strong>Дата создание:</strong> {{ webroom.create|date:"d.m.Y, H:i" }}</p>
  <p><strong>Дата обновления данных:</strong> {{ webroom.update|date:"d.m.Y, H:i" }}</p>
  <p><strong>Успешна ли загрузка на геткурс:</strong> {{ webroom.result_upload }}</p>
  <p><strong>Всего импортировано людей:</strong> {{ webroom.viewersimport_set.count }}</p>
  <p>
    <a href="{{ webroom.get_export_csv_url }}">Получить список импортированных пользователей</a> |
    <a href="{{ webroom.get_import_url }}">Запустить повторный импорт пользователей</a>
  </p>

{% endblock %}

Kizuna/API/templates/webroom/get_webroom.html
{% extends "base_general_template.html" %}

{% load crispy_forms_tags %}

{% block content %}

<h1>Ручной импорт данных из бизона</h1>

<p>Укажите число вебинарных комнат для загрузки из Бизон365</p>
<p>Если хотите получить список без ограничения то сделайте поля дат пустыми</p>

<form action="" method="post" class="w-25 p-3">
    {% csrf_token %}
    <table>
    {{ form|crispy }}
    </table>
    <input type="submit" value="Получить список" />

</form>
{% endblock %}

Kizuna/API/templates/webroom/list_viewers.html
{% extends "base_general_template.html" %}


{% block content %}
    <h1>Список зрителей</h1>

    {% if list_viewers %}
        {% if list_viewers.0 == 'Error' %}
            <h2>{ list.1 }</h2>
        {% else %}
            <ul>

              {% for viewer in list_viewers %}
              <li>
                  <p><b>Email:</b> {{ viewer.email }}</p>
                  <p><b>Phone:</b> {{ viewer.phone }}</p>
                  <p><b>View:</b> {{ viewer.view }} Min</p>
              </li>
              {% endfor %}

            </ul>
        {% endif %}
    {% else %}
      <p>There are no list viewers in the Webinar.</p>
    {% endif %}
{% endblock %}

Kizuna/API/templates/webroom/list_webroom.html
{% extends "base_general_template.html" %}


{% block content %}
    <h1>Список вебинаров</h1>

    {% if webrooms %}
        {% if webrooms.0 == 'Error' %}
            <h2>{ webrooms.1 }</h2>
        {% else %}
            <ul class="list-group">

              {% for web in webrooms %}
              <li class="list-group-item">
                  <p><b>Name:</b> {{ web.webinarId }}</p>
                  <p><b>ID:</b> {{ web.roomid }}</p>
                  <p><b>Create:</b> {{ web.create|date:"d.m.Y, H:i" }} </p>
                  <p><b>Result:</b> {{ web.result_upload }} </p>
                  <p class="w-25 p-3"><a href="{{ web.get_absolute_url }}" class="list-group-item list-group-item-action active">Detail</a> </p>

              </li>
              {% endfor %}

            </ul>
        {% endif %}
    {% else %}
      <p>There are no webroom in the library.</p>
    {% endif %}
{% endblock %}

Kizuna/API/templates/webroom/response_webroom.html
{% extends "base_general_template.html" %}


{% block content %}
    <h1>Webinar List</h1>

    {% if list_webinar %}
    <ul>
      {% for webinar in list_webinar %}

      <li>
          <p><b>Name:</b> {{ webinar.name }}</p>
          <p><b>Type:</b> {{ webinar.type }} </p>
          <p><b>WebinarId:</b> {{ webinar.webinarId }} </p>
          <p><b>Viewers:</b> {{ webinar.count1 }} </p>
          <a href="{% url 'start-hand-import' %}?roomid={{ webinar.name }}&event={{ webinar.type }}&webinarId={{ webinar.webinarId }}">Start Import</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>ERROR.</p>
    {% endif %}
{% endblock %}